import "./globals.css";
import ReduxProvider from "@/store/providers";
import { ToastContainer, toast } from 'react-toastify';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ReduxProvider>
        <ToastContainer />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
